import {red_light,
red_medium ,
red_dark ,
green_light ,
green_medium ,
green_dark ,
blue_light ,
blue_medium ,
blue_dark ,
yellow_light ,
orange_light ,
orange_medium ,
orange_dark ,
purple_light ,
purple_medium ,
purple_dark ,
gray_light ,
gray_medium,
gray_dark ,
white_bright ,
white_off ,
white_eggshell ,
black_light ,
black_medium ,
black_dark } from '../utilities'

export const prototype = {
    colors: {
        danger: red_medium,
        accent: green_light,
        current: blue_medium,
        untouched: gray_medium,
        success: purple,
        info: gray_light,
        mainBg: white_bright,
        cardBg: white_bright,
        lightCardText: white_bright,
        cardText: black_dark,
        darkText: black_dark,
        lightText: white_bright,
        greyText: gray_light,
    },
    fonts: {
        fontName: lato,
        size: {
          heading: '24px',
          subHeading: '18px',
          paragraph: '14px',
          info: '14px',
          large: '48px',
          medium: '24px'
        },
    }
  };